services:
  db:
    image: postgres:15
    #env_file:
     # - /home/sebastian/Desktop/Mis-Cosas/UTN-Seba-Escritorio/5to/2C/Desarrollo-Web/TP/credenciales.env
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/db:/var/lib/postgres/data # Asegurarse que docker-data/db existe
    networks:
      - dbnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    #env_file:
      #- /home/sebastian/Desktop/Mis-Cosas/UTN-Seba-Escritorio/5to/2C/Desarrollo-Web/TP/credenciales.env
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge
